fix fd issues for ce training with extra splits
Summary:
Some folks are still reporiting errors like in P145050739,

```
ValueError: too many fds
```

This diff follows up with D24234470 (https://github.com/pytorch/fairseq/commit/4f320f12d21f17f36e56d04bdb7eba3bbf53b54f), where we add support for `supports_fetch_outside_dataloader` to the rest of the datsets we use, including the sampling datasets enabled by --extra-splits. For why we need to add `supports_fetch_outside_dataloader` see D24234470 (https://github.com/pytorch/fairseq/commit/4f320f12d21f17f36e56d04bdb7eba3bbf53b54f)

Differential Revision: D24767506

fbshipit-source-id: 4e0252f70a9aa36155843677734f186fe03508c4